name: CI (Docker-based)

on:
  push:
    branches: ['**']
  pull_request:
    branches: ['**']

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: ğŸ§¾ Checkout repository
        uses: actions/checkout@v3

      - name: ğŸ³ Build Docker image
        run: DOCKER_BUILDKIT=1 docker build -t esbuild-deploy-ci --progress=plain --platform linux/amd64  -t esbuild-node-deploy:latest -f ./Dockerfile .

      - name: ğŸ“ Prepare test result directory
        run: mkdir -p test-results

      - name: ğŸš€ Run tests in Docker container
        run: docker run --rm -v $PWD/test-results:/src/packages/testing-e2e/test-results esbuild-deploy-ci

      - name: ğŸ“¤ Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: cucumber-results
          path: ./test-results/**

      - name: ğŸ“Š Publish test results to GitHub UI
        uses: mikepenz/action-junit-report@v4
        with:
          report_paths: './test-results/**'